//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubBot2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubBot2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I don&apos;t understand &apos;{0}&apos;. Please try again..
        /// </summary>
        internal static string Do_Not_Understand {
            get {
                return ResourceManager.GetString("Do_Not_Understand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MainBot_Menu {
            get {
                return ResourceManager.GetString("MainBot_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string MoreReply {
            get {
                return ResourceManager.GetString("MoreReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubBot2.1.
        /// </summary>
        internal static string SubBot2_1_Menu {
            get {
                return ResourceManager.GetString("SubBot2_1_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubBot2.2.
        /// </summary>
        internal static string SubBot2_2_Menu {
            get {
                return ResourceManager.GetString("SubBot2_2_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubBot2.3.
        /// </summary>
        internal static string SubBot2_3_Menu {
            get {
                return ResourceManager.GetString("SubBot2_3_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubBot2.
        /// </summary>
        internal static string SubBot2_Menu {
            get {
                return ResourceManager.GetString("SubBot2_Menu", resourceCulture);
            }
        }
    }
}
